tags: null
project_name: test
seed: 0
steps: 188416
log_interval: 10000
eval_episodes: 5
record_fps: 5
eval_interval: null
use_wandb: false
trainer:
  gae_lambda: 0.9
  rollout_len: 1024
  sequence_length: null
  num_envs: 8
  gamma: 0.99
  ent_coef:
    initial: 0.0
  optimizer:
    eps: 1e-7
    learning_rate:
      initial: 0.0001
  seq_model:
    d_model: 124
    n_layers: 2
task:
  name: popgym-NoisyStatelessCartPoleHard-v0
defaults:
  - task: popgym
  - trainer: ppo
  - override trainer/seq_model: lstm
  - _self_