agent: ppo
d_actor: 128
d_critic: 128
num_envs: 8
rollout_len: 256
sequence_length: null
anneal_lr: false
gamma: 0.99
gae_lambda: 0.9
num_minibatches: 4
update_epochs: 10
norm_adv: true
clip_coef: 0.25
ent_coef: 
  initial: 0.0
  final: null
  max_decay_steps: 1000
  power: 1
vf_coef: 1.0
max_grad_norm: 0.5
optimizer:
  eps: 1e-7
  learning_rate: 
    initial: 2.5e-4
    final: null
    max_decay_steps: 1000
    power: 1

defaults:
  - _self_
  - seq_model: lstm